Add setting to choose affiliates list sorting order. #15
AffiliateWP/affiliatewp-checkout-referrals pull request #42
Opened 2021-01-08 16:59 UTC by dbeja

Issue #15 

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

**Implemented changes**
* Add setting on add-on settings to choose the sorting order of the affiliates list
* If the user selects "Alphabetical" it will sort ASC by the "Affiliate Display" setting selected

**Before changes**
<img width="717" alt="imagem" src="https://user-images.githubusercontent.com/498472/104042665-aea59000-51d2-11eb-9642-232c16b3bc58.png">

**After changes**
<img width="717" alt="imagem" src="https://user-images.githubusercontent.com/498472/104042750-c4b35080-51d2-11eb-894b-fe26d7abbe16.png">

2021-01-08 17:01 UTC, dbeja commented
Do I need to regenerate the language files?

2021-01-08 17:53 UTC, DrewAPicture commented
> Do I need to regenerate the language files?

@dbeja As of #25, translations are now handled on .org so no.

2021-01-09 01:21 UTC, DrewAPicture requested changes
Just a few docs nitpicks and other standards fixes needed.

2021-01-09 01:21 UTC, DrewAPicture commented on includes/class-admin.php
> +				'alphabetical' 	=> 'Alphabetical'
```suggestion
				'affiliate_id' 	=> __( 'Affiliate ID', 'affiliatewp-checkout-referrals' ),
				'alphabetical' 	=> __( 'Alphabetical', 'affiliatewp-checkout-referrals' ),
```
The option labels need to be translatable.

2021-01-09 01:21 UTC, DrewAPicture commented on includes/functions.php
> + * Provides a default for when the settings have not yet been saved.
```suggestion
 * Gets the affiliates sorting order.
 *
 * Provides a default for when the settings have not yet been saved.
```
Use a third-person singular verb in the DocBlock summary and add a blank line between the summary and the description.

2021-01-09 01:21 UTC, DrewAPicture commented on includes/functions.php
> + * @return string affiliates sorting order setting
```suggestion
 * @return string Affiliates' sorting order setting.
```
Sentence case for the return description.

2021-01-09 01:21 UTC, DrewAPicture commented on integrations/class-base.php
> +	public function get_affiliates( $args = array() ) {
We're going to need a changelog entry for 1.0.9 for the addition of this optional `$args` parameter as well as an `@param` annotation added to the `get_affiliates()` DocBlock.

2021-01-09 01:21 UTC, DrewAPicture commented on integrations/class-woocommerce.php
> +		$sorting			= affwp_cr_affiliates_sorting_order();
Looks like there's some irregular spacing here. Alignment of variables is typically accomplished using spaces, maybe these are tabs?

2021-01-09 01:21 UTC, DrewAPicture commented on integrations/class-woocommerce.php
> +		if( 'alphabetical' == $sorting ) {
```suggestion
		if ( 'alphabetical' === $sorting ) {
```
When in doubt, strict comparison.

2021-01-11 00:10 UTC, amdrew requested changes
I'm not seeing the affiliates order changing at checkout when testing with Easy Digital Downloads. 

Looking at the PR code, it seems it may only have been implemented for WooCommerce. We'll need to add support for each integration listed (https://affiliatewp.com/add-ons/official-free/checkout-referrals/): WooCommerce, EDD and Restrict Content Pro)

2021-01-11 00:20 UTC, amdrew commented
The ordering (now testing with WooCommerce) doesn't seem to be working as expected. A couple of examples:

## Testing with `Nickname` selected:

<img width="721" alt="Screen Shot 2021-01-11 at 1 11 42 PM" src="https://user-images.githubusercontent.com/52581/104139193-8e621500-540e-11eb-8d9b-3a5154be1f66.png">

Result:

<img width="377" alt="Screen Shot 2021-01-11 at 1 12 29 PM" src="https://user-images.githubusercontent.com/52581/104139204-aa65b680-540e-11eb-8bfc-2103e14b7499.png">

Expected result:

The affiliate with `Aaaaa` as a nickname should appear before `Bbbb`

<img width="805" alt="Screen Shot 2021-01-11 at 1 17 44 PM" src="https://user-images.githubusercontent.com/52581/104139301-7343d500-540f-11eb-830b-b57f295bc28d.png">

<img width="810" alt="Screen Shot 2021-01-11 at 1 18 19 PM" src="https://user-images.githubusercontent.com/52581/104139315-82c31e00-540f-11eb-8ef0-6ec4bbe372e8.png">


---

## Testing with `Display Name`

It's showing "Munro" above `Aaaa`

<img width="728" alt="Screen Shot 2021-01-11 at 1 20 18 PM" src="https://user-images.githubusercontent.com/52581/104139359-c9b11380-540f-11eb-9210-94d61571eda8.png">


<img width="385" alt="Screen Shot 2021-01-11 at 1 16 02 PM" src="https://user-images.githubusercontent.com/52581/104139264-28c25880-540f-11eb-81a4-3f15455a3347.png">

<img width="792" alt="Screen Shot 2021-01-11 at 1 15 47 PM" src="https://user-images.githubusercontent.com/52581/104139259-219b4a80-540f-11eb-8a80-356f758470da.png">

<img width="789" alt="Screen Shot 2021-01-11 at 1 16 17 PM" src="https://user-images.githubusercontent.com/52581/104139272-34158400-540f-11eb-8ea6-02c58e39b3f1.png">

2021-01-11 12:19 UTC, dbeja commented on integrations/class-base.php
> +	public function get_affiliates( $args = array() ) {
I don't need this `$args`var anymore, so I reverted back these changes.

2021-01-11 12:36 UTC, dbeja commented
> The ordering (now testing with WooCommerce) doesn't seem to be working as expected. A couple of examples:

@amdrew By coincidence, I was using a list of Affiliates on my environment that was equal to the same list sorted alphabetically and so it was always working on my side.
The list of affiliates depends on the AffiliatesWP function `affiliate_wp()->affiliates->get_affiliates( $args )` and this function doesn't support sorting the affiliates by neither `Nicename` nor `Nickname`.
Instead of whitelisting those fields on AffiliatesWP core query, I followed another approach. I get the affiliates list sorted by Affiliate ID (as before) and if the user selected `Alphabetical` I sort the list afterwords on PHP side.

2021-01-11 12:39 UTC, dbeja commented
> I'm not seeing the affiliates order changing at checkout when testing with Easy Digital Downloads.
> 
> Looking at the PR code, it seems it may only have been implemented for WooCommerce. We'll need to add support for each integration listed (https://affiliatewp.com/add-ons/official-free/checkout-referrals/): WooCommerce, EDD and Restrict Content Pro)

Missed that. I moved now the function that generates the affiliates list for the "select" to the integrations base class (`class-base.php`) so that it now works on any integration.

2021-01-11 20:56 UTC, amdrew approved these changes
@dbeja Perfecto, all now works as expected 👍

2021-04-09 17:23 UTC, DrewAPicture commented on integrations/class-base.php
> +					<option value="<?php echo $affiliate_id; ?>"><?php echo $affiliate_display; ?></option>
Need `esc_attr()` on the `$affiliate_id` here.
```suggestion
					<option value="<?php echo esc_attr( $affiliate_id ); ?>"><?php echo $affiliate_display; ?></option>
```

2021-04-09 18:09 UTC, DrewAPicture approved these changes
Looks good.

2021-04-09 18:09 UTC, merged