issue/41 Move settings to a dedicated tab
AffiliateWP/affiliatewp-checkout-referrals pull request #44
Opened 2021-01-08 23:13 UTC by dbeja

Issue #41 

**Housekeeping**

* [x] Issue number has been linked below the description
* [x] Branch name follows the `issue/###` or `release/###` format
* [x] PR title is prefixed with the branch name (issue/### - Title)

**Proposed changes**

* [x] Code has been tested with no errors
* [x] Code meets stated minimum requirements
* [x] Code should (usually) not contain unrelated changes
* [x] Code style (including docs) and organization is generally consistent with the rest of the codebase
* [x] Before and after screenshots have been posted to document visual changes
* [x] Clear steps for testing the PR have been posted (as needed)

**Before changes**

<img width="727" alt="imagem" src="https://user-images.githubusercontent.com/498472/104073962-e62e2f80-5206-11eb-9f1f-dd0906946a8c.png">

**After changes**

<img width="1092" alt="imagem" src="https://user-images.githubusercontent.com/498472/104073998-fe05b380-5206-11eb-8a6f-1ad2f23ddf9d.png">

2021-01-11 00:24 UTC, amdrew approved these changes
Works great for me 👍 

<img width="889" alt="Screen Shot 2021-01-11 at 1 23 35 PM" src="https://user-images.githubusercontent.com/52581/104139430-4512c500-5410-11eb-9117-df49cc68c458.png">

2021-01-11 20:54 UTC, DrewAPicture requested changes
Few string-related fixes needed, otherwise it looks good.

2021-01-11 20:54 UTC, DrewAPicture commented on includes/class-admin.php
> +					'nickname'     => 'Nickname'
The option values need to be translatable.

2021-01-11 20:54 UTC, DrewAPicture commented on includes/class-admin.php
> +					'input'       => __( 'Customer enters affiliate\'s ID or username', 'affiliatewp-checkout-referrals'),
The apostrophe in this sentence should be encoded. These various grammar nitpicks are not your fault obviously, but we should fix them while we're here.
```suggestion
					'input'       => __( 'Customer enters affiliate&#8217;s ID or username', 'affiliatewp-checkout-referrals'),
```

2021-01-11 20:54 UTC, DrewAPicture commented on includes/class-admin.php
> +				'desc' => __( 'Customer must select an affiliate to award the referral to', 'affiliatewp-checkout-referrals' ),
There should be a period at the end of this sentence.
```suggestion
				'desc' => __( 'Customer must select an affiliate to award the referral to.', 'affiliatewp-checkout-referrals' ),
```

2021-01-11 20:54 UTC, DrewAPicture commented on includes/class-admin.php
> +				'desc' => __( 'How the affiliates will be displayed at checkout', 'affiliatewp-checkout-referrals' ),
And a period at the end of this sentence also.
```suggestion
				'desc' => __( 'How the affiliates will be displayed at checkout.', 'affiliatewp-checkout-referrals' ),
```

2021-01-11 22:08 UTC, dbeja commented on includes/class-admin.php
> +					'input'       => __( 'Customer enters affiliate\'s ID or username', 'affiliatewp-checkout-referrals'),
Yes, I agree!

2021-01-14 09:29 UTC, DrewAPicture approved these changes
Looks good.

2021-01-18 13:00 UTC, merged